### ISSUE TITLE
Chrome Web Store 404

### ISSUE THREAD

**Issue by AprilNEA** [reorx/github-toc-sidebar#1]

**Comment by reorx** [comment]
Hi, the extension was taken down by Chrome Web Store because they think it was not functioning well, which I believe is a misunderstanding. I have contacted their support to bring it back. It may take several days before this process is finished.

In the meanwhile, you can download the release and install it manually through chrome://extensions developer mode.
https://github.com/reorx/github-toc-sidebar/releases/tag/1.0.0

**Comment by reorx** [comment]
The store page is back online, please leave an review if you think it's useful. Usually I wouldn't ask for this, but this time, it could be helpful to prevent Google from taking it down again.

**Comment by AprilNEA** [comment]
Nice work. I left a review.

**Comment by reorx** [comment]
@AprilNEA thanks ☺️
